server:
  port: 8082

client:
  keycloak:
    client-id: demo-keycloak
    client-secret: PtIaITiCZwkkwbrSdeD77bNURVxEzhFc
    base-url: http://localhost:8080
    realms: demo
    issuer-uri: ${client.keycloak.base-url}/realms/${client.keycloak.realms}

spring:
  application:
    name: "notification"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    activation:
      base-url: "http://localhost:8081/api/auth/verify-email"
  security:
    oauth2:
      resourceserver:
        jwt: #authen by keycloak
          issuer-uri: ${client.keycloak.issuer-uri}
          jwk-set-uri: ${client.keycloak.issuer-uri}/protocol/openid-connect/certs